# Generated by Django 3.1.4 on 2020-12-25 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Passwords_hub', '0003_auto_20201223_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordlist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
